# This notebook is created to do part 2 of Week 3 assignment of Applied Data Science Capstone

### We will find out the latitude and longitude cordinates of each neighborhood so that we could utilize the Foursquare API

#### Step 1 - Lets load the csv file <b>Toronto_Data.csv</b>, we created in Part 1 into a dataframe.

In [1]:
import pandas as pd

# Toronto_data = pd.read_csv("Toronto_Data.csv",index_col = 0)
Toronto_data = pd.read_csv("Toronto_Data.csv")#This csv file is present in the local folder
Toronto_data.sort_values(['Postal Code'], inplace=True,ignore_index = True)
# Toronto_data.reset_index(drop=True)
print(Toronto_data.shape)
Toronto_data

(103, 3)

,Postal Code,Borough,Neighborhood
0,M1B,Scarborough,"Malvern, Rouge"
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek"
2,M1E,Scarborough,"Guildwood, Morningside, West Hill"
3,M1G,Scarborough,Woburn
4,M1H,Scarborough,Cedarbrae
...,...,...,...
98,M9N,York,Weston
99,M9P,Etobicoke,Westmount
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ..."
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest..."
102,M9W,Etobicoke,"Northwest, West Humber - Clairville"

#### Step 2 - Use the geocoder package to find the geographical coordinates of a given postal code

In [ ]:
# # # !pip install geocoder
# import geocoder # import geocoder

# # initialize your variable to None
# lat_lng_coords = None
# # loop until you get the coordinates
# for i in Range(103):
#   print("A") 
#   g = geocoder.google('{}, Toronto, Ontario'.format(Toronto_data["Postal Code"])
#   lat_lng_coords = g.latlng

# latitude = lat_lng_coords[0]
# longitude = lat_lng_coords[1]

# print(latitude)
# print(longitude)
# !conda install -c conda-forge geopy --yes # uncomment this line if you haven't completed the Foursquare API lab
# !pip install geopy
# from geopy.geocoders import Nominatim # convert an address into latitude and longitude values
# latitude = []
# longitude = []

# for postal_code in Toronto_data["Postal Code"]:
#     print(postal_code)
#     address = '{}, Toronto, Ontario'.format(postal_code)

#     geolocator = Nominatim(user_agent="toronto_explorer")
#     location = None
#     while(location is None):
#         print("A")
#         location = geolocator.geocode(address)    
#     latitude.append(location.latitude)
#     longitude.append(location.longitude)
    
# print(latitude)
# print(longitude)
# import geocoder


# def get_geocoder(postal_code_from_df):
#      # initialize your variable to None
#      lat_lng_coords = None
#      # loop until you get the coordinates
#      while(lat_lng_coords is None):
#        g = geocoder.google('{}, Toronto, Ontario'.format(postal_code_from_df))
#        lat_lng_coords = g.latlng
#      latitude = lat_lng_coords[0]
#      longitude = lat_lng_coords[1]
#      return latitude,longitude



# for i in range(0,len(Toronto_data)):
#     Toronto_data['Latitude'][i],Toronto_data['Longitude'][i]=get_geocoder(Toronto_data.iloc[i]['Postal Code'])

##### <b>Reading the given file for longitude and latitude</b>

In [2]:
!wget -q -O Geospatial_Coordinates.csv http://cocl.us/Geospatial_data
print('Data downloaded!')

Data downloaded!

In [3]:
df = pd.read_csv('Geospatial_Coordinates.csv')
df.head()

  Postal Code   Latitude  Longitude
0         M1B  43.806686 -79.194353
1         M1C  43.784535 -79.160497
2         M1E  43.763573 -79.188711
3         M1G  43.770992 -79.216917
4         M1H  43.773136 -79.239476

In [4]:
Toronto_data['Latitude'] = df['Latitude']
Toronto_data['Longitude'] = df['Longitude']
Toronto_data

,Postal Code,Borough,Neighborhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
102,M9W,Etobicoke,"Northwest, West Humber - Clairville",43.706748,-79.594054

In [5]:
Toronto_data.to_csv('Toronto_Final_DataFrame.csv',index=False)